namespace P2PReview.Domain.ConstantsImLazy
{
    public static class ReviewTags
    {
        public static readonly string[] All =
        [
            // Languages
            "C#",
            "Java",
            "Kotlin",
            "JavaScript",
            "TypeScript",
            "Python",
            "Go",
            "Rust",
            "PHP",
            "Swift",
            "Dart",
            "C++",
            "F#",

            // .NET
            "ASP.NET",
            "ASP.NET Core",
            "Entity Framework",
            "EF Core",
            "LINQ",
            "Blazor",
            "MAUI",
            "WPF",
            "WinForms",
            ".NET Aspire",
            "SignalR",
            "MediatR",
            "Minimal API",
            "Web API",
            "Dependency Injection",
            "Middleware",
            "Background Services",
            "Hosted Services",
            "FluentValidation",
            "AutoMapper",
            "Hangfire",
            "Quartz.NET",

            // Frontend
            "React",
            "Next.js",
            "Angular",
            "Vue",
            "Nuxt",
            "Svelte",
            "HTML",
            "CSS",
            "SCSS",
            "Tailwind CSS",
            "Bootstrap",
            "Redux",
            "Zustand",
            "TanStack Query",
            "SSR",
            "CSR",
            "Hydration",
            "Accessibility",
            "State Management",

            // Databases
            "SQL",
            "SQL Server",
            "PostgreSQL",
            "MySQL",
            "SQLite",
            "MongoDB",
            "Redis",
            "ElasticSearch",
            "Database Indexing",
            "Data Modeling",
            "Query Optimization",

            // EF Core & Data Access
            "EF Migrations",
            "Repository Pattern",
            "Unit of Work",
            "Transactions",
            "Optimistic Locking",
            "Pessimistic Locking",
            "Concurrency",
            "N+1",
            "Bulk Operations",

            // APIs
            "REST API",
            "GraphQL",
            "gRPC",
            "WebSockets",
            "OpenAPI",
            "Swagger",

            // Cloud & DevOps
            "Docker",
            "Kubernetes",
            "Azure",
            "AWS",
            "GCP",
            "Terraform",
            "CI/CD",
            "GitHub Actions",
            "Azure DevOps",
            "GitLab CI",

            // Architecture
            "Clean Architecture",
            "DDD",
            "CQRS",
            "Microservices",
            "Monolith",
            "Modular Monolith",
            "Event Sourcing",
            "Event Driven",
            "Vertical Slice",
            "Hexagonal Architecture",
            "Onion Architecture",
            "Layered Architecture",
            "Domain Events",
            "Application Services",
            "Design Patterns",

            // Distributed Systems
            "Distributed Systems",
            "Eventual Consistency",
            "Distributed Transactions",
            "Fault Tolerance",
            "Resilience",
            "Retry Policies",
            "Circuit Breaker",
            "Rate Limiting",
            "Idempotency",
            "Outbox Pattern",
            "Inbox Pattern",
            "Saga Pattern",

            // Messaging
            "Message Brokers",
            "RabbitMQ",
            "Kafka",
            "MassTransit",
            "Message Queue",
            "Pub/Sub",
            "Event Processing",
            "Dead Letter Queue",
            "Consumer Design",
            "Producer Design",

            // Testing
            "Testing",
            "Unit Testing",
            "Integration Testing",
            "E2E Testing",
            "TDD",
            "xUnit",
            "NUnit",
            "Moq",
            "TestContainers",

            // Performance
            "Performance",
            "High Load",
            "Memory Optimization",
            "CPU Optimization",
            "Benchmarking",
            "Profiling",
            "Load Testing",
            "Asynchronous Programming",
            "Parallelism",
            "Multithreading",

            // Security
            "Security",
            "Authentication",
            "Authorization",
            "JWT",
            "OAuth",
            "OpenID Connect",
            "Identity",
            "OWASP",
            "Cryptography",
            "Password Hashing",
            "Secrets Management",
            "CSRF",
            "XSS",
            "SQL Injection",
            "CORS",
            "API Security",
            "Secure Coding",

            // Infrastructure & Observability
            "Logging",
            "Monitoring",
            "Caching",
            "OpenTelemetry",
            "Tracing",
            "Metrics",
            "Structured Logging",
            "Distributed Tracing",
            "Prometheus",
            "Grafana",

            // Mobile
            "Android",
            "iOS",
            "Flutter",
            "React Native",

            // AI
            "AI",
            "Machine Learning",
            "LLM",
            "OpenAI",
            "RAG",
            "Vector Database",
            "Prompt Engineering",
            "AI Agents",
            "MCP",
            "Semantic Kernel",
            "LangChain",
            "Embeddings",
            "Function Calling",
            "Tool Calling",
            "Agentic Systems",

            // Review Topics
            "Refactoring",
            "Code Quality",
            "Best Practices",
            "SOLID",
            "Scalability",
            "Maintainability",
            "Readability",
            "Code Smell",
            "Anti Patterns",
            "Technical Debt",
            "Architecture Review",
            "Bug Hunt",

            // Business Domains
            "Payments",
            "E-Commerce",
            "FinTech",
            "Banking",
            "CRM",
            "ERP",
            "Healthcare",
            "EdTech",
            "Gaming",
            "SaaS",

            // General
            "Algorithms",
            "Data Structures",
            "System Design",
            "Interview Task",
            "Pet Project",
            "Legacy Code",
            "Legacy Refactoring",
            "Startup MVP",
            "Production Bug",
            "Production Incident",
            "Senior Review",
            "System Review",

            // Levels
            "Junior",
            "Middle",
            "Senior",
            "Lead",
            "Staff",
            "Principal"
        ];
    }
}